# Generated by Django 3.1.4 on 2020-12-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindatabase', '0002_person_isvaccinated'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dateofvaccination',
            field=models.DateField(null=True),
        ),
    ]
