# Generated by Django 3.1.4 on 2021-01-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindatabase', '0003_person_dateofvaccination'),
    ]

    operations = [
        migrations.CreateModel(
            name='management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('No_vaccine_dispatched', models.IntegerField()),
                ('No_usable_vaccine', models.IntegerField()),
                ('Temperature', models.IntegerField()),
                ('Humidity', models.IntegerField()),
                ('traffic_density', models.CharField(choices=[('a', 'Low'), ('b', 'Medium'), ('c', 'High')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('aadhar_number', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('Fever', models.BooleanField(default=False)),
                ('Pain_Severity', models.CharField(choices=[('a', 'None'), ('b', 'Low'), ('c', 'Medium'), ('d', 'High')], max_length=1)),
                ('Any_allergies', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='dateofvaccination',
            field=models.DateField(blank=True, null=True),
        ),
    ]
