# Generated by Django 3.1.4 on 2021-01-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindatabase', '0004_auto_20210102_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='id',
        ),
        migrations.AlterField(
            model_name='management',
            name='date_time',
            field=models.DateTimeField(auto_now=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='management',
            name='traffic_density',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='aadhar_number',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='Pain_Severity',
            field=models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='aadhar_number',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
