# Generated by Django 3.0.7 on 2021-01-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindatabase', '0005_auto_20210103_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_without_Aadhar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('area', models.CharField(max_length=200)),
                ('zone', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(default='None', max_length=200)),
                ('isatRisk', models.BooleanField(default=False)),
                ('dateofvaccination', models.DateField(blank=True, null=True)),
                ('isVaccinated', models.BooleanField(default=False)),
            ],
        ),
    ]
