# Generated by Django 3.0.7 on 2021-01-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindatabase', '0006_person_without_aadhar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person_without_aadhar',
            name='image',
        ),
        migrations.AddField(
            model_name='person_without_aadhar',
            name='file',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
