# Generated by Django 3.0.7 on 2021-01-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindatabase', '0007_auto_20210104_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_without_aadhar',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
