# Generated by Django 3.0.7 on 2021-01-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindatabase', '0008_auto_20210104_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_without_aadhar',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
